### ISSUE TITLE
Mention avec un Espace

### ISSUE THREAD

**Issue by AlexandreBourdeaudhui** [O-clock-Dev/formatizer#12]
<img width="170" alt="capture d ecran 2018-04-04 a 15 35 36" src="https://user-images.githubusercontent.com/24500083/38310842-e0ed6e56-381d-11e8-917b-3404be30c10b.png">

**Comment by webdif** [comment]
Ouh, celui-là il risque d'être pas simple 🤔

**Comment by AlexandreBourdeaudhui** [comment]
Je te le laisse 😏 😄

**Comment by webdif** [comment]
https://github.com/O-clock-Dev/formatizer/blob/master/package.json#L8 😏

**Comment by AlexandreBourdeaudhui** [comment]
J'avoue que celui-ci risque d'être « chiant » à faire en fait 🤔

**Comment by oclock-bot-leon** [comment]
Ça fait plus d'un an qu'on n'a pas avancé là-dessus. Cette issue est-elle encore d'actualité ? En l'absence d'une réponse, je me permettrai de fermer l'issue dans un mois.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.

**Comment by Milbrin** [comment]
Faut pas fermer ça Léon :see_no_evil:

**Comment by oclock-bot-leon** [comment]
Ça fait plus d'un an qu'on n'a pas avancé là-dessus. Cette issue est-elle encore d'actualité ? En l'absence d'une réponse, je me permettrai de fermer l'issue dans un mois.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.
