### ISSUE TITLE
Spoiler déjà ouvert pour les profs

### ISSUE THREAD

**Issue by webdif** [O-clock-Dev/formatizer#13]
L'élément `<details>` a un booléen `open` pour savoir si c'est ouvert ou pas, qu'on peut manipuler en javascript (et donc j'imagine en JSX).

Ça serait bien de le mettre à `true` par défaut pour les `isEducator`.
Faudrait passer l'info depuis oLMS, avec une prop.

Tant qu'à faire, on pourrait aussi anticiper d'autres modifs de ce genre, et peut-être se créer une prop pour filer les preferences à formatizer, qui pourra servir à d'autres choses qu'au spoiler.

```
<Formatizer
  options={{
    spoiler: {
      open: isEducator,
    }
  }}
>
  ###
  coucou, je suis un spoiler
  ###
</Formatizer>
```

🤔

**Comment by AlexandreBourdeaudhui** [comment]
J'y ai pensé aussi 👌

**Comment by AlexandreBourdeaudhui** [comment]
Est-ce que du coup on vient changer l'implémentation des options des `@mentions` ?

**Comment by webdif** [comment]
Non on peut laisser comme ça. On peut se dire que si prochainement on a des choses d'affichage à passer on le fait via la prop options, mais sinon pour passer des fonctions ou autre truc un peu plus complexe, on fait une nouvelle prop.
