### ISSUE TITLE
Mentions non prit en compte

### ISSUE THREAD

**Issue by AlexandreBourdeaudhui** [O-clock-Dev/formatizer#15]
Vu ce jour 

<img width="547" alt="capture d ecran 2018-07-12 a 13 35 52" src="https://user-images.githubusercontent.com/24500083/42630862-ab552ce4-85d8-11e8-977b-6d1712cb2803.png">

<img width="483" alt="capture d ecran 2018-07-12 a 13 36 18" src="https://user-images.githubusercontent.com/24500083/42630861-ab3eedf8-85d8-11e8-893c-096350676eb6.png">

**Comment by webdif** [comment]
ça doit être les caractères ! et ' qui ne rentre pas dans la regex

**Comment by AlexandreBourdeaudhui** [comment]
Possible ! C’est marrant comme ils trouvent toujours le moyen de faire des pseudo auxquels on aurait pas pensé 😅

**Comment by webdif** [comment]
Bah c'est surtout que je croyais que le cockpit imposait d'avoir @nom-prenom… J'y comprends rien à cette v1 de toute façon 😄
