### ISSUE TITLE
[V2] - Passage à React V16

### ISSUE THREAD

**Issue by AlexandreBourdeaudhui** [O-clock-Dev/formatizer#17]

**Comment by oclock-bot-leon** [comment]
Ça fait plus d'un an qu'on n'a pas avancé là-dessus. Cette issue est-elle encore d'actualité ? En l'absence d'une réponse, je me permettrai de fermer l'issue dans un mois.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.
