### ISSUE TITLE
Mettre en place système de CI

### ISSUE THREAD

**Issue by AlexandreBourdeaudhui** [O-clock-Dev/formatizer#19]

**Comment by AlexandreBourdeaudhui** [comment]
Ça fonctionne ! Est-ce qu'on se met également le deploy automatique sur NPM, quand ça passe sur master, et que tout est OK ?

**Comment by webdif** [comment]
Oui 💪 !

**Comment by AlexandreBourdeaudhui** [comment]
Cool ! Je mets ça en place dès que possible. Et je fermerais l'issue une fois que c'est fait.

**Comment by AlexandreBourdeaudhui** [comment]
C'est fait. Cependant, je n'ai pas encore testé la mise en ligne sur NPM... Car pas de nouvelle version à mettre en ligne pour le moment (_même si ça ne devrait plus tarder_). Du coup, je ferme.

Je ré-ouvrirai en cas de soucis lors de la publication sur NPM, ou s'il faut affiner certains détails dans la configuration de CircleCI.
