### ISSUE TITLE
Fail share markdown (w/ ###) in snippet

### ISSUE THREAD

**Issue by AlexandreBourdeaudhui** [O-clock-Dev/formatizer#20]
![45038569-c3514680-b061-11e8-8184-5bebd68cf5b4](https://user-images.githubusercontent.com/24500083/53247182-01dfc980-36b3-11e9-88f0-0d683576d36c.png)

--

## Problème : 

Limite d'usage à cette « _feature_ ». Actuellement, le soucis c'est qu'on ne peut pas faire de `code-snippet`, avec des `###` à l'intérieur, sinon ça vient tout casser : 

<img width="592" alt="screenshot 2019-02-20 at 17 03 36" src="https://user-images.githubusercontent.com/24500083/53105563-aa662000-3531-11e9-8646-6171c775c17b.png">

--

## Résultat attendu :

<img width="367" alt="screenshot 2019-02-20 at 17 09 45" src="https://user-images.githubusercontent.com/24500083/53105945-5b6cba80-3532-11e9-91f1-fcc2b2ebb30c.png">

<img width="396" alt="screenshot 2019-02-20 at 17 27 26" src="https://user-images.githubusercontent.com/24500083/53107191-cfa85d80-3534-11e9-8d7b-be9aecf9df96.png">

**Comment by AlexandreBourdeaudhui** [comment]
<img width="398" alt="screenshot 2019-02-25 at 19 03 09" src="https://user-images.githubusercontent.com/24500083/53374437-9b7bd500-3958-11e9-9422-e05d63b1fdb1.png">

~~

Mais si j'ajoute un espace devant les ```, ça ne fonctionne plus... 😞

**Comment by AlexandreBourdeaudhui** [comment]
Cette issue a nécessité un rewrite, et est sur la branche `feature/rewrite`

**Comment by jc-oclock** [comment]
:wave: Je ferme la https://github.com/O-clock-Alumni/Forge/issues/149 mais du coup je up celle-ci :grimacing: coucou @AlexandreBourdeaudhui !

**Comment by oclock-bot-leon** [comment]
Ça fait plus d'un an qu'on n'a pas avancé là-dessus. Cette issue est-elle encore d'actualité ? En l'absence d'une réponse, je me permettrai de fermer l'issue dans un mois.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.
