### ISSUE TITLE
Should detects @mention even after unknow @mention

### ISSUE THREAD

**Issue by AlexandreBourdeaudhui** [O-clock-Dev/formatizer#31]
Continue #20.

- <img width="376" alt="Screenshot 2019-08-09 at 11 46 42" src="https://user-images.githubusercontent.com/24500083/62770480-6a710600-ba9b-11e9-8f94-54f5661fe8f7.png">

- <img width="357" alt="Screenshot 2019-08-09 at 11 46 49" src="https://user-images.githubusercontent.com/24500083/62770481-6a710600-ba9b-11e9-9c96-6062a6a7e107.png">

**Comment by AlexandreBourdeaudhui** [comment]
Si la première mention n'existe pas

- <img width="503" alt="Screenshot 2019-08-09 at 13 07 09" src="https://user-images.githubusercontent.com/24500083/62774957-a65d9880-baa6-11e9-8441-6d0ac690429f.png">

Si la première mention existe

- <img width="679" alt="Screenshot 2019-08-09 at 13 06 57" src="https://user-images.githubusercontent.com/24500083/62774955-a65d9880-baa6-11e9-84b6-54dfa933fbea.png">

**Comment by AlexandreBourdeaudhui** [comment]
Je ne sais pas comment expliquer ça simplement...

Si je prends pour exemple `@fail_mention @question`

- Lorsqu'il va faire un [`const matches = repl.pattern.exec(message);`](https://github.com/O-clock-Dev/formatizer/blob/develop/src/components/Format/getFragments.js#L77), le résultat va être quelque chose comme ça `["@fail_mention", index: 0, input: "@fail_mention @question", groups: undefined]`,


- Ce qui fait que lors du if un peu plus bas, il n'arrivera pas à résoudre cette condition [`(!repl.check || repl.check({ props, match: matches[0] })) &&`](https://github.com/O-clock-Dev/formatizer/blob/develop/src/components/Format/getFragments.js#L83), et ne pourra donc pas splitMessage.


- Ce qui fait qu'il va retourner la string entière, [`@fail_mention @question`](https://github.com/O-clock-Dev/formatizer/blob/develop/src/components/Format/getFragments.js#L109) 😞

**Comment by AlexandreBourdeaudhui** [comment]
Il y a quelque chose qui fonctionne pour le moment, c'est de virer `check`, le "problème" c'est qu'une mention qui n'en est pas une, du style `@fake_mention`, sera détecté comme une `<Mention />`. Pourquoi avons nous mis un `check` en place d'ailleurs ? 🤔

**Comment by Sumsun93** [comment]
J'ai réussi à avancer un peu sur ce bug.
Pour l'instant on peux ecrire `@test @question`
et `@question` sera bien detecté. Par contre si on écrit `@test @question @test @question`
le premier `@question` est detecté mais pas le deuxième 🤔 

<img width="301" alt="Capture d’écran 2019-09-27 à 16 09 51" src="https://user-images.githubusercontent.com/32336668/65775879-4cda2780-e141-11e9-8d6b-9ed0a106a78b.png">

**Comment by oclock-bot-leon** [comment]
Ça fait plus d'un an qu'on n'a pas avancé là-dessus. Cette issue est-elle encore d'actualité ? En l'absence d'une réponse, je me permettrai de fermer l'issue dans un mois.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.
