### ISSUE TITLE
ToolTypes au hover

### ISSUE THREAD

**Issue by Nokama4** [O-clock-Dev/formatizer#5]
Comme sur Slack, il faudrait au hover:

- **D'un Emoji**
  ➡️ Afficher un tooltype avec par exemple :smiley: `:smiley:`
<img width="300" alt="capture d ecran 2018-03-13 a 19 14 23" src="https://user-images.githubusercontent.com/29433595/37362175-d4735e0e-26f4-11e8-94b9-b17635a93bbe.png">

- **D'une Mention**

  ➡️ Afficher un tooltype avec le nom, pseudo et mugshot/avatar   
<img width="300" alt="capture d ecran 2018-03-13 a 19 14 39" src="https://user-images.githubusercontent.com/29433595/37362338-31928a9c-26f5-11e8-9ff3-5c5e1d65f3cf.png">

  ➡️ Afficher le détail de l'utilisateur et donner la possibilité d'envoyer un message privé (A voir si nécessaire? 🤔 )
<img width="200" alt="capture d ecran 2018-03-13 a 19 14 52" src="https://user-images.githubusercontent.com/29433595/37362435-79fc9386-26f5-11e8-9a79-27105f6068bb.png">

**Comment by oclock-bot-leon** [comment]
Ça fait plus d'un an qu'on n'a pas avancé là-dessus. Cette issue est-elle encore d'actualité ? En l'absence d'une réponse, je me permettrai de fermer l'issue dans un mois.

**Comment by oclock-bot-leon** [comment]
Issue obsolète, on ferme.
