### ISSUE TITLE
Mention avec accents

### ISSUE THREAD

**Issue by webdif** [O-clock-Dev/formatizer#6]
https://github.com/O-clock/oLMS/issues/399

Modifier regexp : https://github.com/O-clock-Dev/formatizer/blob/master/src/components/Piece/Mention/index.js#L15

**Comment by AlexandreBourdeaudhui** [comment]
P'tain, j'étais persuadé qu'on utilisait plus la regex... et qu'on venait afficher une mention par rapport à l'user qui se trouve dans la liste 🙃

**Comment by webdif** [comment]
Il faut toujours une regexp pour savoir s'il y a un truc dans le message qui ressemble à une mention, avant qu'on puisse faire le test dessus 🙂 

Mais oui, puisqu'on vérifie derrière si l'user existe, on pourrait se permettre d'être plus souple sur la regexp, du genre `/@\S+/`.

Et faut pas oublier le test d'intégration à rajouter avec un accent dans `{message}` 👍

**Comment by AlexandreBourdeaudhui** [comment]
Oops j'ai oublié de mentionné l'issue dans mon commit.
La release `1.2.2` règle donc ce soucis.
