### ISSUE TITLE
Spoiler ?

### ISSUE THREAD

**Issue by webdif** [O-clock-Dev/formatizer#8]
Issue privée correspondant à l'issue publique https://github.com/O-clock-Alumnis/Forge/issues/69

@Nokama4 @AlexandreBourdeaudhui des idées ?

**Comment by AlexandreBourdeaudhui** [comment]
<details>
  <summary>Spoiler</summary>
  <p>

  Pas d'idée non.
  </p>
</details>

**Comment by webdif** [comment]
Son idée de ### est pas idiote.

```
###
Oui !
###
```

produirait : 

<details><summary>Spoiler</summary>Oui !</details>

 
Et : 
````
###
```
if (alex.isNordiste()) {
  console.log('C’est un spoiler lô ?');
}
```
###
````

produirait un bout de code dans le spoiler (ce qui ne marche pas sur GitHub 🤔)

**Comment by Nokama4** [comment]
J'aimais bien le principe de `spoiler` avant le code, c'est plus rapide à écrire que les 6#.

Mais ça voudrait dire que ce n'est accessible que pour un extrait de code. 🤔

**Comment by webdif** [comment]
> Mais ça voudrait dire que ce n'est accessible que pour un extrait de code. 🤔

Exactement, c'est pour cette raison que je trouve que les ### sont pas trop mal 🤔

**Comment by AlexandreBourdeaudhui** [comment]
> produirait un bout de code dans le spoiler (ce qui ne marche pas sur GitHub 🤔)

Bien-sûr que si, ça fonctionne avec Github ⬇️ 

<details>
  <summary>Spoiler</summary>
  <p>

  ```
	if (alex.isNordiste()) {
	  console.log('C’est un spoiler lô ?');
	}
  ```
  </p>
</details>

**Comment by webdif** [comment]
Au temps pour moi ! Mais faut mettre un <p> pour que ça fonctionne…
Vraiment pas du tout intuitif comme syntaxe.

Du coup, go, on fait avec ### ?

**Comment by AlexandreBourdeaudhui** [comment]
Je suis actuellement dessus vu que je n'avance plus avec le Chemin :)

**Comment by AlexandreBourdeaudhui** [comment]
D'ailleurs ça fonctionne également sans le `<p>`, c'est juste que dans mon copier / coller, je les ai. Faut juste faire attention aux espaces

**Comment by AlexandreBourdeaudhui** [comment]
C'est développé. Manque plus que quelques tests (unitaires + intégration sur le Cockpit) pour que ça soit complètement OP. Je fermerai cette issue une fois que tous les indicateurs seront au vert 💚.

**Comment by AlexandreBourdeaudhui** [comment]
Intégration au Cockpit : 

![mars-28-2018 23-44-21](https://user-images.githubusercontent.com/24500083/38058153-2588e2a2-32e2-11e8-8a3b-b4edd328c9a6.gif)
